// web/src/routes/albums/+page.svelte
<script lang="ts">
  import Header from '$lib/components/elements/tab-header.svelte'
  import type { PageData } from './$types';

  export let data: PageData;
</script>

<svelte:head>
  <title>Albums • mixel-music</title>
</svelte:head>

<Header title={data.title} />

{#if data.albumItem.length > 0}
  <div class="card-grid">
    {#each data.albumItem as tag (tag.albumhash)}
      <div class="card">
        <div
          role="button"
          tabindex=0
          class="card-image-content"
        >
          <img
            loading="lazy"
            src={`http://localhost:2843/api/images/${tag.imagehash}?size=300`}
            alt="{tag.album}"
            class="card-image"
          >
          </div>
        <div class="card-content">
          <span class="text-title">{tag.album}</span>
          <span class="text-description">{tag.albumartist}</span>
        </div>
      </div>
    {/each}
  </div>
{:else}
  <div class="card-placeholder">

  </div>
{/if}

<style>

</style>

// web/src/views/Albums.vue
<template>
  <div class="card-grid">
    <div v-for="(album, index) in fullCardList" :key="album.albumhash" class="card">
      <div v-if="album.album">
        <div class="card-image-content">
          <img v-lazy="`http://localhost:2843/api/images/${ album.imagehash }?size=300`" class="card-image">
        </div>
        <div class="card-content">
          <span class="text-title">{{ album.album }}</span>
          <span class="text-description">{{ album.albumartist }}</span>
        </div>
      </div>
      <div v-else class="card-placeholder">

      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';
import IconamoonPlayCircle from '~icons/iconamoon/play-circle';

export default {
  components: {
    IconamoonPlayCircle,
  },

  data() {
    return {
      info: [],
    };
  },

  created() {
    this.FetchMusicList();
  },

  methods: {
    FetchMusicList() {
      axios.get('http://localhost:2843/api/albums')
        .then(response => {
          this.info = response.data;
        })
        .catch(error => {
          console.error("Failed to fetch:", error);
        });
    },
  },

  computed: {
    fullCardList() {
      const totalItems = 6;
      const emptyItemsToAdd = totalItems - this.info.length;
      const emptyItems = Array.from({ length: emptyItemsToAdd }, () => ({}));
      return [...this.info, ...emptyItems];
    },
  },
}
</script>
