// web/src/components/Player.vue
<template>
  <div class="player">
    <div class="player-length">
      <div class="player-range" @click="LengthSeek($event)" @mousedown="LengthDragStart($event)" @mouseup="DragStop">
        <div class="player-range-length">
          <div class="player-range-now" :style="{ 'width': LengthRangeValue + '%' }"></div>
        </div>
      </div>
    </div>
    <div class="player-left">
      <img v-bind="{ src: path + '?size=128' }" v-if="path">
      <div class="player-left-text">
        <span class="text-title" v-bind="{ title: Title }">{{ Title }}</span>
        <span class="text-description" v-bind="{ title: Artist + ' - ' + Album }" v-if="Title">{{ Artist }} - {{ Album }}</span>
        <span class="text-description" v-bind="{ title: LengthNowFormatted + ' / ' + LengthFormatted }" v-if="Title">{{ LengthNowFormatted }} / {{ LengthFormatted }}</span>
      </div>
    </div>
    <div class="player-center">
      <button class="player-button" title="Previous" @click="PreviousTrack">
        <IconamoonPlayerStartFill />
      </button>
      <button class="player-button player-button-primary" v-bind="{ title: IsPlayNow ? 'Pause' : 'Play' }" @click="ToggleTrack" ref="ToggleButton">
        <IconamoonPlayerPauseFill v-if="IsPlayNow" />
        <IconamoonPlayerPlayFill v-else="IsPlayNow" />
      </button>
      <button class="player-button" title="Next" @click="NextTrack">
        <IconamoonPlayerEndFill />
      </button>
    </div>
    <div class="player-right">
      <div class="player-volume" @mouseover="this.VolumeNowEnable = true" @mouseleave="this.VolumeNowEnable = false">
        <Transition name="ElementFade">
          <div class="player-range" v-bind="{ title: VolumeRangeValue + '%' }" v-if="(VolumeNowEnable || !IsLengthDragNow && IsDragNow)" @click="VolumeSeek($event)" @mousedown="VolumeDragStart($event)" @mouseup="DragStop">
            <div class="player-range-volume">
              <div class="player-range-now" :style="{ 'width': VolumeRangeValue + '%' }"></div>
            </div>
          </div>
        </Transition>
        <button class="player-button" title="Volume" @click="MuteTrack">
          <IconamoonVolumeUp v-if="VolumeRangeValue >= 50" />
          <IconamoonVolumeDown v-else-if="VolumeRangeValue < 50 && VolumeRangeValue != 0" />
          <IconamoonVolumeOff v-else />
        </button>
      </div>
      <button class="player-button" v-bind="{ title: Repeat == 0 || Repeat == 1 ? 'Repeat' : 'Repeat one' }" :class="{ 'button-disabled': Repeat == 0 }" @click="RepeatTracks()">
        <IconamoonPlaylistRepeatList v-if="Repeat == 0 || Repeat == 1"/>
        <IconamoonPlaylistRepeatSong v-else />
      </button>
      <button class="player-button" title="Shuffle" :class="{ 'button-disabled': !Shuffle }" @click="Shuffle = true">
        <IconamoonPlaylistShuffle />
      </button>
      <button class="player-button button-end" title="Play queue">
        <IconamoonPlaylist />
      </button>
    </div>
  </div>
</template>

<script>
import IconamoonPlayerPauseFill from '~icons/iconamoon/player-pause-fill';
import IconamoonPlayerPlayFill from '~icons/iconamoon/player-play-fill';
import IconamoonPlayerStartFill from '~icons/iconamoon/player-start-fill';
import IconamoonPlayerEndFill from '~icons/iconamoon/player-end-fill';

import IconamoonVolumeUp from '~icons/iconamoon/volume-up';
import IconamoonVolumeDown from '~icons/iconamoon/volume-down';
import IconamoonVolumeOff from '~icons/iconamoon/volume-off';

import IconamoonPlaylistRepeatList from '~icons/iconamoon/playlist-repeat-list';
import IconamoonPlaylistRepeatSong from '~icons/iconamoon/playlist-repeat-song';
import IconamoonPlaylistShuffle from '~icons/iconamoon/playlist-shuffle';
import IconamoonPlaylist from '~icons/iconamoon/playlist';

import IconamoonHeart from '~icons/iconamoon/heart';
import IconamoonHeartFill from '~icons/iconamoon/heart-fill';
import IconamoonMenuKebabHorizontal from '~icons/iconamoon/menu-kebab-horizontal';

export default {
  components: {
    IconamoonPlayerPauseFill,
    IconamoonPlayerPlayFill,
    IconamoonPlayerStartFill,
    IconamoonPlayerEndFill,

    IconamoonVolumeUp,
    IconamoonVolumeDown,
    IconamoonVolumeOff,

    IconamoonPlaylistRepeatList,
    IconamoonPlaylistRepeatSong,
    IconamoonPlaylistShuffle,
    IconamoonPlaylist,

    IconamoonHeart,
    IconamoonHeartFill,
    IconamoonMenuKebabHorizontal,
  },

  data() {
    return {
      Music: new Audio(),
      Title: null,
      Album: null,
      Artist: null,
      path: null,

      Length: 0, // RAW Value (sec, float)
      LengthNow: 0, // RAW Value (sec, float)

      VolumeNow: 1, // RAW Value (0~1)
      VolumeNowEnable: false,

      Repeat: 0,
      Shuffle: false,

      IsDragNow: false,
      IsLengthDragNow: false,
      IsPlayNow: false,
    }
  },

  created() {
    this.Music.addEventListener('timeupdate', this.UpdateTime);
    this.Music.addEventListener('loadedmetadata', () => {
      this.Length = this.Music.duration;
    });
  },

  beforeUnmount() {
    this.Music.removeEventListener('timeupdate', this.UpdateTime);
    this.Music.removeEventListener('loadedmetadata');
    this.Music.removeEventListener('ended', this.HandleMusicEnd);
    window.removeEventListener('keydown', this.HandleSpace);
    this.Music.pause();

    if (this.IsDragNow) {
      document.removeEventListener('mousemove', this.LengthDrag);
      document.removeEventListener('mousemove', this.DragStart);
      document.removeEventListener('mousemove', this.DragStop);
    }
  },

  mounted() {
    this.Music.addEventListener('ended', this.HandleMusicEnd);
    window.addEventListener('keydown', this.HandleSpace);
  },

  computed: {
    LengthNowFormatted() {
      return this.FormatTime(this.LengthNow);
    },

    LengthFormatted() {
      return this.FormatTime(this.Length);
    },

    LengthRangeValue() {
      return (this.LengthNow / this.Length * 100).toFixed(2); // Formatted(int), 0 to 100
    },

    VolumeRangeValue() {
      return Math.floor(this.VolumeNow * 100); // Formatted(int), 0 to 100
    },
  },

  methods: {
    SelectTrack(title, album, artist, path) {
      this.Title = title;
      this.Album = album;
      this.Artist = artist;
      this.Music.src = `http://localhost:2843/api/v1/stream/${path}`;
      this.path = `http://localhost:2843/api/v1/images/${path}`;

      if (this.Music.paused) {
        this.Music.play();
        this.IsPlayNow = true;
        document.title = this.Title + ' - mixel-music';
        this.SetMediaControls();
      }
    },

    HandleSpace(event) {
      if (event.key === ' ' || event.keyCode === 32) {
        if (this.$refs.ToggleButton === document.activeElement || document.activeElement === document.body) {
          event.preventDefault();
          this.ToggleTrack();
        }
      }
    },
    
    SetMediaControls: function () {
      if ('mediaSession' in navigator) {
        navigator.mediaSession.metadata = new MediaMetadata({
          title: this.Title,
          album: this.Album,
          artist: this.Artist,
          artwork: [
            {
              src: this.path + "?size=300",
            }  
          ],
        });

        navigator.mediaSession.setActionHandler("play", () => { this.ToggleTrack(); });
        navigator.mediaSession.setActionHandler("pause", () => { this.ToggleTrack(); });
        navigator.mediaSession.setActionHandler("seekbackward", () => { this.Music.currentTime -= 10; });
        navigator.mediaSession.setActionHandler("seekforward", () => { this.Music.currentTime += 10; });
        navigator.mediaSession.setActionHandler("previoustrack", () => { this.PreviousTrack();});
        navigator.mediaSession.setActionHandler("nexttrack", () => { this.NextTrack(); });
      }
    },

    UpdateTime() {
      if (!this.IsDragNow) this.LengthNow = this.Music.currentTime;
      this.MusicSlider = (this.MusicCurrent / this.MusicDuration) * 100;
      if (!this.IsDrag && this.MusicCurrent >= this.MusicDuration) {
        this.resetPlayer();
        document.title = 'mixel-music';
      }
    },

    FormatTime(time) {
      const min = Math.floor(time / 60);
      const sec = Math.floor(time % 60);
      return `${min}:${sec < 10 ? '0' : ''}${sec}`;
    },

    PreviousTrack() {
      this.Music.currentTime = 0;
    },

    ToggleTrack() {
      if (!this.IsDragNow && this.Music.paused && this.LengthNow >= this.Length && this.LengthNow != 0) {
        this.LengthNow = 0;
        this.Music.play();
        this.IsPlayNow = true;
        this.SetMediaControls();
      }
      else if (this.Music.paused) {
        if (this.Music.src) {
          this.Music.play();
          document.title = this.Title + ' - mixel-music';
          this.IsPlayNow = true;
          this.SetMediaControls();
        }
        else {
          console.warn("DEBUG: Select any tracks to play");
        }
      }
      else {
        this.Music.pause();
        this.IsPlayNow = false;
        this.SetMediaControls();
      }
    },

    NextTrack() {
      console.log("Test");
    },

    HandleMusicEnd() {
      if (!this.IsDragNow) {
        this.IsPlayNow = false;
        this.Music.pause();
        this.SetMediaControls();
        document.title = 'mixel-music';
      }
    },

    HandleRangeMove(event, RangeClass, callback) {
      const Range = this.$el.querySelector(RangeClass);
      const RangeWidth = Range.clientWidth;
      const MouseLocation = event.clientX - Range.getBoundingClientRect().left;
      const NewRangeValue = MouseLocation / RangeWidth;
      callback(NewRangeValue);
    },

    LengthSeek(event) {
      this.HandleRangeMove(event, '.player-range-length', value => {
        this.Music.currentTime = value * this.Length;
        this.LengthNow = this.Music.currentTime;
      });
    },

    VolumeSeek(event) {
      this.HandleRangeMove(event, '.player-range-volume', value => {
        this.Music.volume = Math.min(Math.max(value, 0), 1);
        this.VolumeNow = this.Music.volume;
        if (this.VolumeNow != 0) {
          this.Music.muted = false;
        }
        else {
          this.Music.muted = true;
        }
      });
    },
    
    LengthDragStart(event) {
      if(this.IsPlayNow) {
        this.IsDragNow = true;
        this.IsLengthDragNow = true;
        document.addEventListener('mousemove', this.LengthDragStart);
        document.addEventListener('mouseup', this.DragStop);
        this.HandleRangeMove(event, '.player-range-length', value => {
          this.LengthNow = Math.min(Math.max(value * this.Length, 0), this.Music.duration - 0.1);
          this.Music.currentTime = this.LengthNow;
        });
      }
    },

    VolumeDragStart(event) {
      this.IsDragNow = true;
      document.addEventListener('mousemove', this.VolumeDragStart);
      document.addEventListener('mouseup', this.DragStop);
      this.HandleRangeMove(event, '.player-range-volume', value => {
        this.Music.volume = Math.min(Math.max(value, 0), 1);
        this.VolumeNow = this.Music.volume;
        if (this.VolumeNow != 0) {
          this.Music.muted = false;
        }
        else {
          this.Music.muted = true;
        }
      });
    },

    DragStop() {
      this.IsDragNow = false;
      this.IsLengthDragNow = false;
      document.removeEventListener('mousemove', this.LengthDragStart);
      document.removeEventListener('mousemove', this.VolumeDragStart);
      document.removeEventListener('mouseup', this.DragStop);
    },

    MuteTrack() {
      if (this.Music.muted) {
        this.Music.muted = false;
        if (this.Music.volume == 0) {
          this.VolumeNow = this.Music.volume = 0.1;
        }
        else {
          this.VolumeNow = this.Music.volume;
        }
      }
      else {
        this.Music.muted = true;
        this.VolumeNow = 0;
      }
    },

    RepeatTracks() {
      if (this.Repeat == 0) {
        this.Repeat = 1;
        this.Music.loop = true;
      }
      else if (this.Repeat == 1) {
        this.Repeat = 2;
        this.Music.loop = true;
      }
      else {
        this.Repeat = 0;
        this.Music.loop = false;
      }
    },
  }
}
</script>

// web/src/lib/components/layouts/player/player.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { hash, title, album, artist, imagehash } from '$lib/stores';

  import ContentHead from '$lib/components/elements/content-head.svelte';
  import ContentBody from '$lib/components/elements/content-body.svelte';
  import PlayerButton from './player-button.svelte';
  import PlayerSlider from './player-slider.svelte';

  let audioItem: HTMLAudioElement = new Audio();
  let imagepath: string = "";
  let durationTime: number = 0;
  let currentTime: number = 0;
  let durationString: string = formatTime(0);
  let currentString: string = formatTime(0);
  let currentBar: number = 0;
  let volumeBar: number = 100;
  let isPlaying: boolean = false;
  let isDraggingLength: boolean = false;
  let isDraggingVolume: boolean = false;
  let isRepeatTrack: number = 0;

  $: $title, loadAudio();

  function handlePlay(): void {
    if ($hash !== undefined) {
      if (audioItem.paused) {
        audioItem.play();
        isPlaying = true;
      }
      else {
        audioItem.pause();
        isPlaying = false;
      }
    }
  }

  function previousPlay(): void {
    audioItem.currentTime = 0;
  }

  function loadAudio() {
    if ($hash !== undefined) {
      audioItem.src = (`http://localhost:2843/api/stream/${$hash}`);
      imagepath = `http://localhost:2843/api/images/${$imagehash}`;
      audioItem.volume = volumeBar / 100;

      audioItem.addEventListener("loadedmetadata", () => {
        durationTime = audioItem.duration;
        durationString = formatTime(audioItem.duration);
        currentString = formatTime(audioItem.currentTime);

        audioItem.play();
        isPlaying = true;
        setMediaControls();
      });

      audioItem.addEventListener("timeupdate", () => {
        if (!isDraggingLength) {
          currentTime = audioItem.currentTime;
          currentString = formatTime(currentTime);
          currentBar = (currentTime / durationTime) * 100;
        }

        if (audioItem.currentTime === audioItem.duration) {
          isPlaying = false;
          audioItem.pause();
          setMediaControls();
        }
      });
    }

    // audioItem.addEventListener("error", () => {
    //   console.error("Failed to load track");
    // });
  }

  function setMediaControls(): void {
    if ('mediaSession' in navigator) {
      navigator.mediaSession.metadata = new MediaMetadata({
        title: $title,
        album: $album,
        artist: $artist,
        artwork: [
          {
            src: imagepath + "?size=300",
          }  
        ],
      });

      navigator.mediaSession.setActionHandler("play", () => { handlePlay(); });
      navigator.mediaSession.setActionHandler("pause", () => { handlePlay(); });
      navigator.mediaSession.setActionHandler("seekbackward", () => { audioItem.currentTime -= 10; });
      navigator.mediaSession.setActionHandler("seekforward", () => { audioItem.currentTime += 10; });
      navigator.mediaSession.setActionHandler("previoustrack", () => { previousPlay(); });
      navigator.mediaSession.setActionHandler("nexttrack", () => { console.log("test") });
    }
  }

  function handleSeek(event: MouseEvent, eventClass: string, callback: (value: number) => void): void {
    event.preventDefault();

    const ctl = document.querySelector(eventClass);
    if (ctl) {
      const ctlWidth = ctl.clientWidth;
      const ctlRect = ctl.getBoundingClientRect();
      const newValue = Math.max(0, Math.min(event.clientX - ctlRect.left, ctlWidth));
      const newValueCalc = newValue / ctlWidth;
      callback(newValueCalc);
    }
  }

  function lengthSeek(event: MouseEvent): void {
    handleSeek(event, '.length-ctl', (value) => {
      if (audioItem) {
        currentTime = value * durationTime;
        currentString = formatTime(currentTime);
        currentBar = value * 100;
        if (!isDraggingLength) {
          audioItem.currentTime = currentTime;
        }
      }
    });
  }

  function volumeSeek(event: MouseEvent): void {
    handleSeek(event, '.volume-ctl', (value) => {
      volumeBar = value * 100;
      if (audioItem) {
        audioItem.volume = value;
      }
    });
  }

  function handleDragStart(event: MouseEvent, type: 'length' | 'volume'): void {
    event.preventDefault();
    if (type === "length") {
      isDraggingLength = true;
    } else {
      isDraggingVolume = true;
    }

    const handleMove = type === "length" ? lengthSeek : volumeSeek;
    const handleEnd = () => {
      if (type === "length") {
        isDraggingLength = false;
        if (audioItem) {
          audioItem.currentTime = currentTime;
        }
      } else {
        isDraggingVolume = false;
      }
      document.removeEventListener("mousemove", handleMove);
      document.removeEventListener("mouseup", handleEnd);
    };

    document.addEventListener("mousemove", handleMove);
    document.addEventListener("mouseup", handleEnd);
    handleMove(event);
  }

  function formatTime(time: number): string {
    const min = Math.floor(time / 60);
    const sec = Math.floor(time % 60);
    return `${min}:${sec < 10 ? "0" : ""}${sec}`;
  }

  function muteVolume(): void {
    if (audioItem.volume === 0) {
      audioItem.volume = 1;
      audioItem.muted = false;
      volumeBar = 100;
    }
    else if (!audioItem.muted) {
      audioItem.muted = true;
    }
    else {
      audioItem.muted = false;
    }
  }

  function repeatTrack(): void {
    if (isRepeatTrack === 0) {
      isRepeatTrack = 1;
      audioItem.loop = true;
    }
    else if (isRepeatTrack === 1) {
      isRepeatTrack = 2;
      audioItem.loop = true;
    }
    else {
      isRepeatTrack = 0;
      audioItem.loop = false;
    }
  }

  onDestroy(() => {
    if (audioItem) {
      audioItem.src = '';
    }
  });
</script>

<div class="player">
  <div class="player-center">

    <div class="player-button">

      <PlayerButton
        title='Previous'
        on:click={previousPlay}
        icon='iconoir:skip-prev-solid'
        control_button
      />

      <PlayerButton
        title={isPlaying ? 'Pause' : 'Play'}
        on:click={handlePlay}
        icon={isPlaying ? 'iconoir:pause-solid' : 'iconoir:play-solid'}
        control_button
        primary_button
      />

      <PlayerButton
        title='Next'
        on:click={undefined}
        icon='iconoir:skip-next-solid'
        control_button
      />

    </div>

    <PlayerSlider
      width='550px'
      value={currentBar}
      unique='length-ctl'
      on:click={(event) => lengthSeek(event)}
      on:mousedown={(event => handleDragStart(event, 'length'))}  
    />

  </div>

  <div class="player-area">
    <div class="player-area-1">

      {#if $hash}
        <img
          src="{imagepath}?size=128"
          class="player-cover"
          alt="Front Cover"
        />

        <div class="player-track">
          <ContentHead head='{$title ? $title : ""}' />
          <ContentBody body='{$artist ? $artist : ""} - {$album ? $album : ""}' />
          <ContentBody body='{ currentString } / { durationString }' />
        </div>
      {/if}

    </div>

    <div class="player-area-2">
      <div class="player-volume">

        {#key muteVolume}
          <PlayerSlider
            width='110px'
            unique='volume-ctl'
            value={audioItem.muted ? 0 : volumeBar}
            on:click={(event) => volumeSeek(event)}
            on:mousedown={(event) => handleDragStart(event, "volume")}  
          />

          <PlayerButton
            title="Volume"
            on:click={muteVolume}
            turn_off={volumeBar === 0 || audioItem.muted ? true : false}
            icon={
              volumeBar === 0 || audioItem.muted ? 'iconoir:sound-off' :
                volumeBar < 50 ? 'iconoir:sound-low' : 'iconoir-sound-high'
            }
          />
        {/key}

      </div>

      <PlayerButton
        title={
          isRepeatTrack == 2 ? 'Repeat one' : 'Repeat'
        }
        icon={
          isRepeatTrack === 1 ? 'iconoir:repeat' :
            isRepeatTrack === 2 ? 'iconoir-repeat-once' : 'iconoir-repeat'
        }
        turn_off={isRepeatTrack !== 0 ? false : true}
        on:click={repeatTrack}
      />

      <PlayerButton
        title='Shuffle'
        icon='iconoir:shuffle'
        turn_off
      />

      <PlayerButton
        title='Playlist'
        icon='iconoir:playlist'
      />

    </div>
  </div>
</div>

<style>
  .player {
    display: flex;
    align-items: center;
    justify-content: space-between;
    position: fixed;
    bottom: 0;
    z-index: 2;
    width: 100%;
    height: 96px;
    background-color: var(--color-dark-bg-trk);
    backdrop-filter: blur(64px);
    user-select: none;
    border-top: 1px solid var(--color-dark-border);
    box-shadow: 0 0 0 1px var(--color-dark-border) inset;
  }

  .player-area {
    width: 100%;
    display: flex;
    padding: 0 21px;
    justify-content: space-between;
  }

  .player-area-1 {
    display: flex;
    align-items: center;
    gap: var(--app-padding-s);
  }

  .player-area-2 {
    display: flex;
    align-items: center;
  }

  .player-cover {
    width: 56px;
    height: 56px;
    object-fit: scale-down;
    background-color: var(--color-dark-bg-2);
    box-shadow: 0 0 0 1px var(--color-dark-border) inset;
    border-radius: var(--app-radius);
    cursor: pointer;
  }

  .player-track {
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
    line-height: 120%;
  }

  .player-center {
    position: fixed;
    left: 50%;
    transform: translate(-50%, 0);
  }

  .player-button {
    display: flex;
    justify-content: center;
    padding: 4px 8px;
  }

  .player-volume {
    display: flex;
    align-items: center;
  }
</style>
