// web/src/lib/components/layouts/sidebar/sidebar.svelte
<script lang="ts">
  import SidebarSection from '$lib/components/layouts/sidebar/sidebar-section.svelte';
  import SidebarItem from '$lib/components/layouts/sidebar/sidebar-item.svelte';
</script>

<div>
  <SidebarSection>
      <SidebarItem link="/" title="Home" />
      <SidebarItem link="/" title="Search" />
      <SidebarItem link="/" title="My Mix" />
  </SidebarSection>

  <SidebarSection title="Library">
    <SidebarItem
      link="/albums"
      title="Albums"
      icon="iconoir:compact-disc"
    />
    <SidebarItem
      link="/artists"
      title="Artists"
      icon="iconoir:microphone"
      />
    <SidebarItem
      link="/tracks"
      title="Tracks"
      icon="iconoir:music-double-note"
    />
  </SidebarSection>
  
  <SidebarSection title="PlayLists">
    <SidebarItem
      link=""
      title="Create Playlist"
      icon="iconoir:plus"
    />
  </SidebarSection>
</div>

<style>
  div {
    position: fixed;
    width: 250px;
    height: 100%;

    top: 0;
    left: 0;
    z-index: 0;

    padding: 24px 21px;
    background-color: var(--color-dark-bg-2);
    border-right: 1px solid var(--color-dark-border);
  }
</style>

// web/src/components/Sidebar.vue
<template>
  <div class="sidebar-item sidebar-item-top">
    <router-link to="/" class="sidebar-text">
      <!-- <IconamoonHome class="sidebar-icon" /> -->
      Home
    </router-link>
  </div>
  <div class="sidebar-item">
    <router-link to="/" class="sidebar-text">
      Search
    </router-link>
  </div>
  <div class="sidebar-item">
    <router-link to="/" class="sidebar-text">
      Library
    </router-link>
  </div>
  <div class="sidebar-divider"></div>
    <div class="sidebar-item">
    <router-link to="/albums" class="sidebar-link">
      <IconamoonMusicAlbum class="sidebar-icon" />
      &nbsp;
      Albums
    </router-link>
  </div>
  <div class="sidebar-item">
    <router-link to="/tracks" class="sidebar-link">
      <IconamoonMusic2 class="sidebar-icon" />
      &nbsp;
      Songs
    </router-link>
  </div>
  <div class="sidebar-item">
    <router-link to="/artists" class="sidebar-link">
      <IconamoonMusicArtist class="sidebar-icon" />
      &nbsp;
      Artists
    </router-link>
  </div>
  <div class="sidebar-item">
    <router-link to="/mixes" class="sidebar-link">
      <IconamoonHeadphone class="sidebar-icon" />
      &nbsp;
      Radios
    </router-link>
  </div>
  <div class="sidebar-divider"></div>
  <div class="sidebar-item">
    <router-link to="/playlists" class="sidebar-text sidebar-link-playlist">
      Playlists
      <IconamoonSignPlus />
    </router-link>
  </div>
</template>

<script>
import IconamoonHome from '~icons/iconamoon/home';
import IconamoonPlaylist from '~icons/iconamoon/playlist';
import IconamoonMusicAlbum from '~icons/iconamoon/music-album';
import IconamoonMusic2 from '~icons/iconamoon/music-2';
import IconamoonMusicArtist from '~icons/iconamoon/music-artist';
import IconamoonHeadphone from '~icons/iconamoon/headphone';
import IconamoonSignPlus from '~icons/iconamoon/sign-plus';

export default {
  components: {
    IconamoonHome,
    IconamoonMusicAlbum,
    IconamoonMusic2,
    IconamoonMusicArtist,
    IconamoonPlaylist,
    IconamoonHeadphone,
    IconamoonSignPlus,
  },
}
</script>
