// web/src/components/player.vue
<template>
  <div class="player">
    <div class="player-left">
      <p class="text-title">{{ Title }}</p>
      <p class="text-description">{{ Artist }} - {{ Album }}</p>
      <p class="text-description">{{ LengthNowFormatted }} / {{ LengthFormatted }}</p>
    </div>
    <div class="player-center">
      <button class="player-button" @click="PreviousTrack">
        <IconamoonPlayerStartFill />
      </button>
      <button class="player-button player-button-primary" @click="ToggleTrack">
        <IconamoonPlayerPauseFill v-if="IsPlayNow" />
        <IconamoonPlayerPlayFill v-else="IsPlayNow" />
      </button>
      <button class="player-button" @click="NextTrack">
        <IconamoonPlayerEndFill />
      </button>
      <div class="player-range" @click="LengthSeek($event)" @mousedown="LengthDragStart($event)" @mouseup="DragStop">
        <div class="player-range-length">
          <div class="player-range-now" :style="{ 'width': LengthRangeValue + '%' }"></div>
        </div>
      </div>
    </div>
    <div class="player-right">
      <div class="player-volume" v-bind="{ title: VolumeRangeValue + '%' }" @mouseover="this.VolumeNowEnable = true" @mouseleave="this.VolumeNowEnable = false">
        <!--<Transition name="ElementFade">-->
          <div class="player-range" v-if="(VolumeNowEnable || !IsLengthDragNow && IsDragNow)" @click="VolumeSeek($event)" @mousedown="VolumeDragStart($event)" @mouseup="DragStop">
            <div class="player-range-volume">
              <div class="player-range-now" :style="{ 'width': VolumeRangeValue + '%' }"></div>
            </div>
          </div>
        <!--</Transition>-->
        <button class="player-button" @click="MuteTrack">
          <IconamoonVolumeOff v-if="VolumeRangeValue == 0 || Music.muted" />
          <IconamoonVolumeUp v-else-if="VolumeRangeValue >= 50" />
          <IconamoonVolumeDown v-else-if="VolumeRangeValue < 50" />
        </button>
      </div>
      <button class="player-button" :class="{ 'button-disabled': Repeat == 0 }" @click="RepeatTracks()">
        <IconamoonPlaylistRepeatList v-if="Repeat == 0 || Repeat == 1"/>
        <IconamoonPlaylistRepeatSong v-else />
      </button>
      <button class="player-button">
        <IconamoonHeart />
      </button>
      <button class="player-button">
        <IconamoonPlaylist />
      </button>
      <button class="player-button">
        <IconamoonMenuKebabHorizontal />
      </button>
    </div>
  </div>
</template>

<script>
import IconamoonPlayerPauseFill from '~icons/iconamoon/player-pause-fill';
import IconamoonPlayerPlayFill from '~icons/iconamoon/player-play-fill';
import IconamoonPlayerStartFill from '~icons/iconamoon/player-start-fill';
import IconamoonPlayerEndFill from '~icons/iconamoon/player-end-fill';

import IconamoonVolumeUp from '~icons/iconamoon/volume-up';
import IconamoonVolumeDown from '~icons/iconamoon/volume-down';
import IconamoonVolumeOff from '~icons/iconamoon/volume-off';

import IconamoonPlaylistRepeatList from '~icons/iconamoon/playlist-repeat-list';
import IconamoonPlaylistRepeatSong from '~icons/iconamoon/playlist-repeat-song';
import IconamoonPlaylistShuffle from '~icons/iconamoon/playlist-shuffle';
import IconamoonPlaylist from '~icons/iconamoon/playlist';

import IconamoonHeart from '~icons/iconamoon/heart';
import IconamoonHeartFill from '~icons/iconamoon/heart-fill';
import IconamoonMenuKebabHorizontal from '~icons/iconamoon/menu-kebab-horizontal';

export default {
  components: {
    IconamoonPlayerPauseFill,
    IconamoonPlayerPlayFill,
    IconamoonPlayerStartFill,
    IconamoonPlayerEndFill,

    IconamoonVolumeUp,
    IconamoonVolumeDown,
    IconamoonVolumeOff,

    IconamoonPlaylistRepeatList,
    IconamoonPlaylistRepeatSong,
    IconamoonPlaylistShuffle,
    IconamoonPlaylist,

    IconamoonHeart,
    IconamoonHeartFill,
    IconamoonMenuKebabHorizontal,
  },

  data() {
    return {
      Music: new Audio(),
      Title: null,
      Album: null,
      Artist: null,

      Length: 0, // RAW Value
      LengthNow: 0, // RAW Value

      VolumeNow: 1, // RAW Value (0 to 1)
      VolumeNowEnable: false,

      Repeat: 0,

      IsDragNow: false,
      IsLengthDragNow: false,
      IsPlayNow: false,
    }
  },

  created() {
    this.Music.addEventListener('timeupdate', this.UpdateTime);
    this.Music.addEventListener('loadedmetadata', () => {
      this.Length = this.Music.duration;
    });
  },

  beforeUnmount() {
    this.Music.removeEventListener('timeupdate', this.UpdateTime);
    this.Music.removeEventListener('loadedmetadata', () => {
      this.Length = this.Music.duration;
    });
    this.Music.removeEventListener('ended', this.HandleMusicEnd);
    this.Music.pause();

    if (this.IsDragNow) {
      document.removeEventListener('mousemove', this.LengthDrag);
      document.removeEventListener('mousemove', this.DragStart);
      document.removeEventListener('mousemove', this.DragStop);
    }
  },

  mounted() {
    this.Music.addEventListener('ended', this.HandleMusicEnd);
  },

  computed: {
    LengthNowFormatted() {
      return this.FormatTime(this.LengthNow);
    },

    LengthFormatted() {
      return this.FormatTime(this.Length);
    },

    LengthRangeValue() {
      return (this.LengthNow / this.Length * 100).toFixed(2); // Formatted(int), 0 to 100
    },

    VolumeRangeValue() {
      return Math.floor(this.VolumeNow * 100); // Formatted(int), 0 to 100
    },
  },

  methods: {
    FormatTime(time) {
      const min = Math.floor(time / 60);
      const sec = Math.floor(time % 60);
      return `${min}:${sec < 10 ? '0' : ''}${sec}`;
    },

    SetMediaControls: function () {
      if ('mediaSession' in navigator) {
        navigator.mediaSession.metadata = new MediaMetadata({
          title: this.Title,
          album: this.Album,
          artist: this.Artist,
          artwork: [],
        });

        navigator.mediaSession.setActionHandler("play", () => { this.Resume(); });
        navigator.mediaSession.setActionHandler("pause", () => { this.Resume(); });
        navigator.mediaSession.setActionHandler("stop", () => { this.Resume(); });
        navigator.mediaSession.setActionHandler("seekbackward", () => { this.Resume(); });
        navigator.mediaSession.setActionHandler("seekforward", () => { this.Resume(); });
        navigator.mediaSession.setActionHandler("seekto", () => { this.Resume(); });
        navigator.mediaSession.setActionHandler("previoustrack", () => { this.Resume(); });
        navigator.mediaSession.setActionHandler("nexttrack", () => { this.Resume(); });
      }
    },

    SelectTrack(title, album, artist, path) {
      this.Title = title;
      this.Album = album;
      this.Artist = artist;
      this.Music.src = `http://localhost:8000/api/stream/${path}`;

      if (this.Music.paused) {
        this.Music.play();
        this.IsPlayNow = true;
        this.SetMediaControls();
      }
    },

    ToggleTrack() {
      if (!this.IsDragNow && this.Music.paused && this.LengthNow >= this.Length && this.LengthNow != 0) {
        this.LengthNow = 0;
        this.Music.play();
        this.IsPlayNow = true;
        this.SetMediaControls();
      }
      else if (this.Music.paused) {
        if (this.Music.src) {
          this.Music.play();
          this.IsPlayNow = true;
          this.SetMediaControls();
        }
        else {
          console.warn("DEBUG: Select any tracks to play");
        }
      }
      else {
        this.Music.pause();
        this.IsPlayNow = false;
        this.SetMediaControls();
      }
    },

    PreviousTrack() {
      this.Music.currentTime = 0;
    },

    HandleMusicEnd() {
      if (!this.IsDragNow) {
        this.IsPlayNow = false;
        this.Music.pause();
      }
    },

    NextTrack() {
      console.log("Test");
    },

    MuteTrack() {
      if (this.Music.muted != true) {
        this.Music.muted = true;
        this.VolumeNow = 0;
      }
      else {
        this.Music.muted = false;
        this.VolumeNow = this.Music.volume;
      }
    },

    RepeatTracks() {
      if (this.Repeat == 0) {
        this.Repeat = 1;
        this.Music.loop = true;
      }
      else if (this.Repeat == 1) {
        this.Repeat = 2;
        this.Music.loop = true;
      }
      else {
        this.Repeat = 0;
        this.Music.loop = false;
      }
    },

    UpdateTime() {
      if (!this.IsDragNow) this.LengthNow = this.Music.currentTime;
      this.MusicSlider = (this.MusicCurrent / this.MusicDuration) * 100;
      if (!this.IsDrag && this.MusicCurrent >= this.MusicDuration) {
        this.resetPlayer();
      }
    },

    HandleRangeMove(event, RangeClass, callback) {
      const Range = this.$el.querySelector(RangeClass);
      const RangeWidth = Range.clientWidth;
      const MouseLocation = event.clientX - Range.getBoundingClientRect().left;
      const NewRangeValue = MouseLocation / RangeWidth;
      callback(NewRangeValue);
    },

    LengthSeek(event) {
      this.HandleRangeMove(event, '.player-range-length', value => {
        this.Music.currentTime = value * this.Length;
        this.LengthNow = this.Music.currentTime;
      });
    },

    VolumeSeek(event) {
      this.HandleRangeMove(event, '.player-range-volume', value => {
        this.Music.volume = Math.min(Math.max(value, 0), 1);
        this.VolumeNow = this.Music.volume;
      });
    },
    
    LengthDragStart(event) {
      if(this.IsPlayNow) {
        this.IsDragNow = true;
        this.IsLengthDragNow = true;
        document.addEventListener('mousemove', this.LengthDragStart);
        document.addEventListener('mouseup', this.DragStop);
        this.HandleRangeMove(event, '.player-range-length', value => {
          this.LengthNow = Math.min(Math.max(value * this.Length, 0), this.Music.duration - 0.1);
          this.Music.currentTime = this.LengthNow;
        });
      }
    },

    VolumeDragStart(event) {
      this.IsDragNow = true;
      document.addEventListener('mousemove', this.VolumeDragStart);
      document.addEventListener('mouseup', this.DragStop);
      this.HandleRangeMove(event, '.player-range-volume', value => {
        this.Music.volume = Math.min(Math.max(value, 0), 1);
        this.VolumeNow = this.Music.volume;
      });
    },

    DragStop() {
      this.IsDragNow = false;
      this.IsLengthDragNow = false;
      document.removeEventListener('mousemove', this.LengthDragStart);
      document.removeEventListener('mousemove', this.VolumeDragStart);
      document.removeEventListener('mouseup', this.DragStop);
    },
  }
}
</script>

// web/src/lib/components/Player.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { hash, title, album, artist, imagehash } from '$lib/stores';

  import IconamoonPlayerPauseFill from '~icons/iconamoon/player-pause-fill';
  import IconamoonPlayerPlayFill from '~icons/iconamoon/player-play-fill';
  import IconamoonPlayerStartFill from '~icons/iconamoon/player-start-fill';
  import IconamoonPlayerEndFill from '~icons/iconamoon/player-end-fill';
  import IconamoonVolumeUp from '~icons/iconamoon/volume-up';
  import IconamoonVolumeDown from '~icons/iconamoon/volume-down';
  import IconamoonVolumeOff from '~icons/iconamoon/volume-off';
  import IconamoonPlaylistRepeatList from '~icons/iconamoon/playlist-repeat-list';
  import IconamoonPlaylistRepeatSong from '~icons/iconamoon/playlist-repeat-song';
  import IconamoonPlaylistShuffle from '~icons/iconamoon/playlist-shuffle';
  import IconamoonPlaylist from '~icons/iconamoon/playlist';
  import Page from "../../routes/+page.svelte";

  let audioItem: HTMLAudioElement = new Audio();
  let imagepath: string = "";

  let durationTime: number = 0;
  let currentTime: number = 0;

  let durationString: string = formatTime(0);
  let currentString: string = formatTime(0);

  let currentBar: number = 0;
  let volumeBar: number = 100;

  let isPlaying: boolean = false;
  let isDraggingLength: boolean = false;
  let isDraggingVolume: boolean = false;
  let isRepeatTrack: number = 0;

  $: $hash, loadAudio();

  function handlePlay(): void {
    if (audioItem.paused) {
      audioItem.play();
      isPlaying = true;
    }
    else {
      audioItem.pause();
      isPlaying = false;
    }
  }

  function previousPlay(): void {
    audioItem.currentTime = 0;
  }

  function loadAudio() {
    audioItem.src = (`http://localhost:2843/api/stream/${$hash}`);
    imagepath = `http://localhost:2843/api/images/${$imagehash}`;
    audioItem.volume = volumeBar / 100;

    audioItem.addEventListener("loadedmetadata", () => {
      durationTime = audioItem.duration;
      durationString = formatTime(audioItem.duration);
      currentString = formatTime(audioItem.currentTime);

      audioItem.play();
      isPlaying = true;
      setMediaControls();
    });

    audioItem.addEventListener("timeupdate", () => {
      if (!isDraggingLength) {
        currentTime = audioItem.currentTime;
        currentString = formatTime(currentTime);
        currentBar = (currentTime / durationTime) * 100;
      }
    });

    // audioItem.addEventListener("error", () => {
    //   console.error("Failed to load track");
    // });
  }

  function setMediaControls(): void {
    if ('mediaSession' in navigator) {
      navigator.mediaSession.metadata = new MediaMetadata({
        title: $title,
        album: $album,
        artist: $artist,
        artwork: [
          {
            src: imagepath + "?size=300",
          }  
        ],
      });

      navigator.mediaSession.setActionHandler("play", () => { handlePlay(); });
      navigator.mediaSession.setActionHandler("pause", () => { handlePlay(); });
      navigator.mediaSession.setActionHandler("seekbackward", () => { audioItem.currentTime -= 10; });
      navigator.mediaSession.setActionHandler("seekforward", () => { audioItem.currentTime += 10; });
      navigator.mediaSession.setActionHandler("previoustrack", () => { previousPlay(); });
      navigator.mediaSession.setActionHandler("nexttrack", () => { console.log("test") });
    }
  }

  function handleSeek(event: MouseEvent, eventClass: string, callback: (value: number) => void): void {
    event.preventDefault();

    const ctl = document.querySelector(eventClass);
    if (ctl) {
      const ctlWidth = ctl.clientWidth;
      const ctlRect = ctl.getBoundingClientRect();
      const newValue = Math.max(0, Math.min(event.clientX - ctlRect.left, ctlWidth));
      const newValueCalc = newValue / ctlWidth;
      callback(newValueCalc);
    }
  }

  function lengthSeek(event: MouseEvent): void {
    handleSeek(event, '.player-length-ctl', (value) => {
      if (audioItem) {
        currentTime = value * durationTime;
        currentString = formatTime(currentTime);
        currentBar = value * 100;
        if (!isDraggingLength) {
          audioItem.currentTime = currentTime;
        }
      }
    });
  }

  function volumeSeek(event: MouseEvent): void {
    handleSeek(event, '.player-volume-ctl', (value) => {
      volumeBar = value * 100;
      if (audioItem) {
        audioItem.volume = value;
      }
    });
  }

  function handleDragStart(event: MouseEvent, type: "length" | "volume"): void {
    event.preventDefault();
    if (type === "length") {
      isDraggingLength = true;
    } else {
      isDraggingVolume = true;
    }
    const handleMove = type === "length" ? lengthSeek : volumeSeek;
    const handleEnd = () => {
      if (type === "length") {
        isDraggingLength = false;
        if (audioItem) {
          audioItem.currentTime = currentTime;
        }
      } else {
        isDraggingVolume = false;
      }
      document.removeEventListener("mousemove", handleMove);
      document.removeEventListener("mouseup", handleEnd);
    };
    document.addEventListener("mousemove", handleMove);
    document.addEventListener("mouseup", handleEnd);
    handleMove(event);
  }

  function formatTime(time: number): string {
    const min = Math.floor(time / 60);
    const sec = Math.floor(time % 60);
    return `${min}:${sec < 10 ? "0" : ""}${sec}`;
  }

  function muteVolume(): void {
    if (audioItem.volume === 0) {
      audioItem.volume = 1;
      audioItem.muted = false;
      volumeBar = 100;
    }
    else if (!audioItem.muted) {
      audioItem.muted = true;
    }
    else {
      audioItem.muted = false;
    }
  }

  function repeatTrack(): void {
    if (isRepeatTrack === 0) {
      isRepeatTrack = 1;
      audioItem.loop = true;
    }
    else if (isRepeatTrack === 1) {
      isRepeatTrack = 2;
      audioItem.loop = true;
    }
    else {
      isRepeatTrack = 0;
      audioItem.loop = false;
    }
  }

  onDestroy(() => {
    if (audioItem) {
      audioItem.src = '';
    }
  });
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div class="player">
  <div
    tabindex=0
    role="slider"
    class="player-length"
    on:click={(event) => lengthSeek(event)}
    on:mousedown={(event) => handleDragStart(event, "length")}
  >
    <div class="player-length-ctl">
      <div
        class="player-length-ctl__now"
        style="width: {currentBar}%;"
      />
    </div>
  </div>
  <div class="player-area">
    <div class="player-area-1">
      {#if $hash}
        <img
          src="{imagepath}?size=128"
          class="player-area-1-img"
          alt="Front Cover"
        />
        <div class="player-area-1-trk">
          <span class="text-title">
            {$title ? $title : ""}
          </span>
          <span class="text-description">
            {$artist ? $artist : ""} - {$album ? $album : ""}
          </span>
          <span class="text-description">
            {currentString} / {durationString}
          </span>
        </div>
      {/if}
    </div>
    <div class="player-area-2">
      <button
        class="player-area-btn"
        on:click={previousPlay}
        title="Previous"
      >
        <IconamoonPlayerStartFill />
      </button>
      {#if $hash}
        <button
          class="player-area-btn btn-primary"
          on:click={handlePlay}
        >
          {#if isPlaying}
            <IconamoonPlayerPauseFill />
          {:else}
            <IconamoonPlayerPlayFill />
          {/if}
        </button>
      {:else}
        <button class="player-area-btn btn-primary">
          <IconamoonPlayerPlayFill />
        </button>
      {/if}
      <button class="player-area-btn" title="Next">
        <IconamoonPlayerEndFill />
      </button>
    </div>
    <div class="player-area-3">
      <div class="player-volume">
        {#key muteVolume}
          <div
            tabindex=0
            role="slider"
            class="player-volume-ctl"
            on:click={(event) => volumeSeek(event)}
            on:mousedown={(event) => handleDragStart(event, "volume")}  
          >
            <div
              class="player-volume-ctl__now"
              style="width: {audioItem.muted ? 0 : volumeBar}%;"
            />
          </div>
          <button
            class="player-side-btn"
            title="Volume"
            on:click={muteVolume}
          >
            {#if volumeBar === 0 || audioItem.muted}
              <IconamoonVolumeOff />
            {:else if volumeBar < 50}
              <IconamoonVolumeDown />
            {:else}
              <IconamoonVolumeUp />
            {/if}
          </button>
        {/key}
      </div>
      <button
        class="player-side-btn { isRepeatTrack == 0 ? 'player-btn__disabled' : ''}"
        title={isRepeatTrack == 2 ? 'Repeat one' : 'Repeat'}
        on:click={repeatTrack}
      >
        {#if isRepeatTrack === 1}
          <IconamoonPlaylistRepeatList />
        {:else if isRepeatTrack === 2}
          <IconamoonPlaylistRepeatSong />
        {:else}
          <IconamoonPlaylistRepeatList />
        {/if}
      </button>
      <button class="player-side-btn" title="Shuffle">
        <IconamoonPlaylistShuffle />
      </button>
      <button class="player-side-btn" title="Playlist">
        <IconamoonPlaylist />
      </button>
    </div>
  </div>
</div>

<style>
.player {
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: fixed;
  bottom: 0;
  width: 100%;
  height: 96px;
  background-color: var(--color-dark-trk);
  backdrop-filter: blur(32px);
  user-select: none;
}

.player-area {
  width: 100%;
  display: flex;
  padding: 0 16px;
  justify-content: space-between;
}

.player-area-1 {
  display: flex;
  align-items: center;
  gap: var(--app-padding-s);
  height: 56px;
}

.player-area-1-img {
  width: 56px;
  height: 56px;
  object-fit: scale-down;
  background-color: var(--color-dark-bg-2);
  box-shadow: 0 0 0 1px var(--color-dark-border) inset;
  border-radius: var(--app-radius);
  cursor: pointer;
}

.player-area-1-trk {
  display: flex;
  flex-direction: column;
  justify-content: space-evenly;
  line-height: 120%;
}

.player-area-2 {
  display: flex;
  position: fixed;
  left: 50%;
  transform: translate(-50%, 0);
  height: 56px;
}

.player-area-btn {
  display: flex;
  padding: 12px;
  border: none;
  background-color: transparent;
  color: var(--color-dark-text-1);
  font-size: 20px;
  cursor: pointer;
  transition: 0.2s ease;
  align-items: center;
  justify-content: center;
}

.player-area-btn:focus {
  outline: none;
}

.player-area-btn:hover {
  color: var(--color-dark-focus);
  transition: all 0.1s ease;
}

.btn-primary {
  font-size: 28px;
  margin: 0 10px;
}

.player-area-3 {
  display: flex;
  align-items: center;
}

.player-side-btn {
  display: flex;
  padding: 12px;
  border: none;
  background-color: transparent;
  color: var(--color-dark-text-1);
  font-size: 18px;
  cursor: pointer;
  transition: 0.2s ease;
  align-items: center;
  justify-content: center;
}

.player-length {
  height: 3px;
  background-color: var(--color-dark-trk-len);
  border-radius: var(--app-radius);
  position: fixed;
  left: 0;
  bottom: 93px;
  width: 100%;
}

.player-length-ctl {
  padding-bottom: 12px;
  cursor: pointer;
}

.player-length-ctl__now {
  width: 0;
  height: 3px;
  background-color: var(--color-dark-trk-now);
  border-radius: var(--app-radius);
}

.player-volume {
  display: flex;
  align-items: center;
}

.player-volume-ctl {
  width: 100px;
  height: 3px;
  cursor: pointer;
  padding: 12px;
  background-color: var(--color-dark-trk-len);
  border-radius: var(--app-radius);
  background-clip: content-box;
}

.player-volume-ctl__now {
  width: 30px;
  height: 3px;
  background-color: var(--color-dark-trk-now);
  border-radius: var(--app-radius);
}

.player-btn__disabled {
  color: var(--color-dark-disabled);
}
</style>
