// web/src/components/Navbar.vue
<template>
  <nav class="navbar">
    <div class="navbar-left">
      <button class="navbar-button navbar-previous" @click="$router.back()">
        <IconamoonArrowLeft2 class="navbar-icon" />
      </button>
      <button class="navbar-button navbar-next" @click="$router.go(1)">
        <IconamoonArrowRight2 class="navbar-icon" />
      </button>
    </div>
    <div class="navbar-center">
      
    </div>
    <div class="navbar-right">
      <input type="text" name="Search" placeholder="Search">
    </div>
  </nav>
</template>

<script>
import IconamoonArrowLeft2 from '~icons/iconamoon/arrow-left-2';
import IconamoonArrowRight2 from '~icons/iconamoon/arrow-right-2';

export default {
  components: {
    IconamoonArrowLeft2,
    IconamoonArrowRight2,
  },
}
</script>

// web/src/lib/components/layouts/navbar/navbar.svelte
<script lang="ts">
  import ButtonRd from '$lib/components/elements/button-rd.svelte';
  import TextBox from '$lib/components/elements/textbox.svelte';
  import Icon from '@iconify/svelte';
</script>

<nav>
  <div>
    <ButtonRd on:click={() => history.back()}>
      <Icon icon="iconoir:nav-arrow-left" />
    </ButtonRd>
    <ButtonRd on:click={() => history.forward()}>
      <Icon icon="iconoir:nav-arrow-right" />
    </ButtonRd>
  </div>

  <div>
    <TextBox
      name="search"
      type="search"
      width="290px"
      placeholder="Search"
    />
    <ButtonRd>
      <Icon icon="iconoir:refresh" />
    </ButtonRd>
    <ButtonRd>
      <Icon icon="iconoir:user" />
    </ButtonRd>
  </div>
</nav>

<style>
  nav {
    position: sticky;
    max-width: 100%;
    top: 0;

    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 24px 0;
  }

  div {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
  }
</style>
